name: flutter_app
description: "A new Flutter project."


publish_to: 'none' 













version: 1.0.0+1

environment:
  sdk: ^3.5.3







dependencies:
  flutter:
    sdk: flutter


  
  
  cupertino_icons: ^1.0.8
  provider: 
  flutter_native_splash: ^2.4.0
  stroke_text: ^0.0.3
  http: ^1.2.1
  flutter_secure_storage: ^9.2.2
  image_picker: ^1.1.2
  permission_handler: ^11.3.1


dev_dependencies:
  flutter_test:
    sdk: flutter

  
  
  
  
  
  flutter_lints: ^4.0.0





flutter:

  
  
  
  uses-material-design: true

  
  
  
  

  
  

  flutter:
  fonts:
    - family: CascadiaMonoPL
      fonts:
        - asset: assets/fonts/CascadiaMonoPL-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/CascadiaMonoPL-ExtraLightItalic.ttf
          weight: 200
          style: italic
        - asset: assets/fonts/CascadiaMonoPL-Light.ttf
          weight: 300
        - asset: assets/fonts/CascadiaMonoPL-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/CascadiaMonoPL-Regular.ttf
          weight: 400
        - asset: assets/fonts/CascadiaMonoPL-Italic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/CascadiaMonoPL-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/CascadiaMonoPL-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/CascadiaMonoPL-SemiLight.ttf
          weight: 500
        - asset: assets/fonts/CascadiaMonoPL-SemiLightItalic.ttf
          weight: 500
          style: italic

    - family: CascadiaMono
      fonts:
        - asset: assets/fonts/CascadiaMono-Bold.ttf
          weight: 700
        - asset: assets/fonts/CascadiaMono-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/CascadiaMono-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/CascadiaMono-ExtraLightItalic.ttf
          weight: 200
          style: italic
        - asset: assets/fonts/CascadiaMono-Light.ttf
          weight: 300
        - asset: assets/fonts/CascadiaMono-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/CascadiaMono-Regular.ttf
          weight: 400
        - asset: assets/fonts/CascadiaMono-Italic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/CascadiaMono-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/CascadiaMono-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/CascadiaMono-SemiLight.ttf
          weight: 500
        - asset: assets/fonts/CascadiaMono-SemiLightItalic.ttf
          weight: 500
          style: italic
